services:
  accounts:
    image: enzogavini/accounts:1.0.0
    ports:
      - "8080:8080"
    mem_limit: 700m

  cards:
    image: enzogavini/cards:1.0.0
    ports:
      - "9000:9000"
    mem_limit: 700m

  loans:
    image: enzogavini/loans:1.0.0
    ports:
      - "8090:8090"
    mem_limit: 700m